#!/bin/bash
SAMPLERATE_LIB_DIR="$(pwd)/gosamplerate/lib"
DOWNLOAD_URL='http://www.mega-nerd.com/SRC/libsamplerate-0.1.9.tar.gz'

cd /tmp
wget $DOWNLOAD_URL -O /tmp/libsamplerate.tar.gz > /dev/null 2>&1
tar -xf libsamplerate.tar.gz > /dev/null 2>&1
cd libsamplerate-0.1.9

# This shouldnt throw any errors, but just in case I have it logging the error codes.
# The logs are a bit spammy, didn't want to clog up logs.

echo "Configuring libsamplerate (Step 1/3)"
./configure --enable-static \
    --enable-shared=no \
    --prefix=$SAMPLERATE_LIB_DIR \
    --include=$SAMPLERATE_LIB_DIR \
    --libdir=$SAMPLERATE_LIB_DIR > /dev/null 2>&1
echo "Finished configuring with exit code $?. Now building libsamplerate (Step 2/3)"
make > /dev/null 2>&1
echo "Finished building with exit code $?. Now installing libsamplerate (Step 3/3)"
make install > /dev/null 2>&1

# Remove all un-needed files

rm -r $SAMPLERATE_LIB_DIR/bin $SAMPLERATE_LIB_DIR/pkgconfig $SAMPLERATE_LIB_DIR/share $SAMPLERATE_LIB_DIR/libsamplerate.la
echo "Finished installing libsamplerate with exit code $?."