#!/bin/bash

EXPECTED="	not a dynamic executable"

test() {
    got=$1
    expected=$2
    name=$3
    if [ "$got" = "$expected" ]; then
        echo "$name got a static executable as expected"
    else
        echo "Expected to get"
        echo "$EXPECTED"
        echo "But recieved"
        echo "$got"
        echo "$got"
        echo "$expected"
        echo "$EXPECTED"
        exit
    fi
}

echo "Testing opus"
cd opus && go build -o opus
cd ..

test "$(ldd opus/opus)" "$EXPECTED" opus
cd gosamplerate && go build -o gosamplerate
cd ..

test "$(ldd gosamplerate/gosamplerate)" "$EXPECTED" gosamplerate

echo "All tests passed"
